name: LevelRestrictions
main: com.github.mineGeek.LevelRestrictions.LevelRestrictions
version: 1.0.0
commands:
    lrcan:
        description: List of what you can do at your level
        aliases: [can, cando]
        usage: /lrcan [full]
        permission-message: You don't have permission fool
    lrcant:
        description: a list of what you can't do
        aliases: [cant, cantdo, lrcant]
        usage: /lrcant [full]
        permission-message: You don't have permission fool
    lrfull:
        description: a list of what you can and cannot do
        aliases: [full, rfull]
        usage: /lrfull [all]
        permisson-message: You don't have permission for this
    lrcreate:
        description: creates a new rule
        usage: /lrcreate rulename
        permission: LevelRestrictions.admin.create
        permission-message: You lack the skillz for this
    lrkillrule:
        description: deletes an existing rule
        usage: /lrkillrule rulename
        permission: LevelRestrictions.admin.killrule
        permission-message: DENIED!
    lredit:
        description: allows you to edit a rule.
        usage: /lredit rulename [desc|min|max|addaction|removeaction|additem|removeitem] value
        permission: LevelRestrictions.admin.create
        permission-message: fail. you no haz perms.
    lrdump:
        description: outputs rules to screen
        permission: LevelRestrictions.admin