name: LevelRestrictions
main: com.github.mineGeek.LevelRestrictions.LevelRestrictions
version: 0.0.1
commands:
    lrcan:
        description: List of what you can do at your level
        aliases: [can, cando]
        usage: /lrcan [full]
        permission-message: You don't have permission fool
    lrcant:
        description: a list of what you can't do
        aliases: [cant, cantdo, lrcant]
        usage: /lrcant [full]
        permission-message: You don't have permission fool
    lrfull:
        description: a list of what you can and cannot do
        aliases: [full, rfull]
        usage: /lrfull [all]
        permisson-message: You don't have permission for this